"""Export helpers writing pgfplots-readable tables into ``pics/data``.

Every experiment writes plain whitespace-separated tables with a single header
row of column names, which ``\\addplot table[x=..,y=..]`` consumes directly.  The
figures in ``pics/*.tex`` are therefore pure LaTeX and inherit the document's
fonts, and re-running an experiment updates the figures without touching any
TeX source.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
DATA_OUT = REPO / "pics" / "data"

__all__ = ["DATA_OUT", "write_table", "write_matrix", "write_macros"]


def write_table(name: str, columns: dict, *, comment: str = "", fmt: str = "%.10g") -> Path:
    """Write named equal-length columns to ``pics/data/<name>.dat``."""
    DATA_OUT.mkdir(parents=True, exist_ok=True)
    keys = list(columns)
    cols = [np.atleast_1d(np.asarray(columns[k], dtype=float)).ravel() for k in keys]
    n = len(cols[0])
    if any(len(c) != n for c in cols):
        raise ValueError(f"columns of unequal length: "
                         f"{ {k: len(c) for k, c in zip(keys, cols)} }")
    path = DATA_OUT / f"{name}.dat"
    with path.open("w") as fh:
        if comment:
            for line in comment.strip().splitlines():
                fh.write(f"# {line.strip()}\n")
        fh.write(" ".join(keys) + "\n")
        for row in np.column_stack(cols):
            fh.write(" ".join(fmt % v for v in row) + "\n")
    return path


def write_matrix(name: str, x, y, z, *, xname="x", yname="y", zname="z",
                 comment: str = "", fmt: str = "%.10g") -> Path:
    """Write a 2-D field as a blank-line-separated table for ``matrix plot``.

    ``z`` has shape ``(len(y), len(x))``.  pgfplots needs a blank line between
    consecutive scan lines to recognise the mesh structure.
    """
    DATA_OUT.mkdir(parents=True, exist_ok=True)
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    z = np.asarray(z, dtype=float)
    if z.shape != (len(y), len(x)):
        raise ValueError(f"z has shape {z.shape}, expected {(len(y), len(x))}")
    path = DATA_OUT / f"{name}.dat"
    with path.open("w") as fh:
        if comment:
            for line in comment.strip().splitlines():
                fh.write(f"# {line.strip()}\n")
        fh.write(f"{xname} {yname} {zname}\n")
        for j, yy in enumerate(y):
            for i, xx in enumerate(x):
                fh.write(f"{fmt % xx} {fmt % yy} {fmt % z[j, i]}\n")
            fh.write("\n")
    return path


def write_macros(name: str, macros: dict, *, comment: str = "") -> Path:
    """Write ``\\newcommand`` definitions so numbers quoted in the text stay in sync.

    Keys must be alphabetic (TeX macro names cannot contain digits); values are
    written verbatim, so pre-format them as strings.
    """
    DATA_OUT.mkdir(parents=True, exist_ok=True)
    path = DATA_OUT / f"{name}.tex"
    with path.open("w") as fh:
        fh.write("% Generated by the experiments in python/experiments -- do not edit.\n")
        if comment:
            for line in comment.strip().splitlines():
                fh.write(f"% {line.strip()}\n")
        for key, value in macros.items():
            if not key.isalpha():
                raise ValueError(f"macro name {key!r} must be purely alphabetic")
            fh.write(f"\\newcommand{{\\{key}}}{{{value}}}\n")
    return path


def sci(value: float, digits: int = 2) -> str:
    """Format a number as LaTeX scientific notation, e.g. ``1.07\\cdot 10^{-20}``.

    Macros are consumed inside math mode in the manuscript, so a bare Python
    ``%e`` string such as ``1.07e-20`` would typeset as an expression rather than
    a number.
    """
    s = f"%.{digits}e" % float(value)
    mantissa, exponent = s.split("e")
    exp = int(exponent)
    if exp == 0:
        return mantissa
    return f"{mantissa}\\cdot 10^{{{exp}}}"


def banner(title: str) -> None:
    """Consistent section header in experiment console output."""
    line = "=" * max(8, len(title) + 4)
    print(f"\n{line}\n  {title}\n{line}")
